"use client";
import Link from "next/link";
import { AppShell, ErrorState, LoadingState } from "@/components/ui";
import { BarChart3, Boxes, Download, Info, Package, RefreshCw, Search, ShoppingBag, TrendingUp, Wallet } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";

type Row = { order_id:string; purchase_time:string; conversion_status:string; order_status:string; item_name:string; shop_name:string; actual_amount:number; commission:number; seller_commission_rate?:number; shopee_commission_rate?:number };
type Data = { connected:boolean; summary:{estimated:number;confirmed:number;pending:number;gmv:number;orders:number;pendingOrders:number;units:number}; topProducts:{name:string;units:number;commission:number}[]; topShops:{name:string;orders:number;commission:number}[]; daily:{date:string;orders:number;commission:number;units:number;gmv:number}[]; details:{rows:Row[];total:number;page:number;pageSize:number}; statusOptions:string[]; sync?:{last_success_at?:string;last_error?:string} };
const money = new Intl.NumberFormat("pt-BR", { style:"currency", currency:"BRL" });
const statusLabels:Record<string,string>={PENDING:"Pendente",COMPLETED:"Confirmado",CANCELLED:"Cancelado",UNPAID:"Não pago",ALL:"Todos"};
const isoDate = (date:Date) => { const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,"0"),d=String(date.getDate()).padStart(2,"0"); return `${y}-${m}-${d}`; };
const initial=()=>{const to=new Date();to.setDate(to.getDate()-1);const from=new Date(to);from.setDate(from.getDate()-6);return{from:isoDate(from),to:isoDate(to)}};

export default function ShopeeAnalyticsPage(){
 const preset=initial(),[from,setFrom]=useState(preset.from),[to,setTo]=useState(preset.to),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(20),[search,setSearch]=useState(""),[status,setStatus]=useState("ALL"),[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[syncing,setSyncing]=useState(false);
 const load=useCallback(async(force=false)=>{setError("");force?setSyncing(true):setLoading(true);try{const q=new URLSearchParams({from,to,page:String(page),pageSize:String(pageSize),search,status});const r=await fetch(`/api/analytics/shopee?${q}`,{method:force?"POST":"GET",cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error);setData(b)}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar.")}finally{setLoading(false);setSyncing(false)}},[from,to,page,pageSize,search,status]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),search?350:0);return()=>clearTimeout(timer)},[load,search]);
 function presetRange(kind:string){const now=new Date(),end=new Date(now);end.setDate(end.getDate()-1);let start=new Date(end);if(kind==="yesterday")start=end;else if(kind==="7")start.setDate(start.getDate()-6);else{start=new Date(now.getFullYear(),now.getMonth(),1);end.setDate(now.getDate()-1)}return{from:isoDate(start),to:isoDate(end)}}
 function quick(kind:string){const r=presetRange(kind);setFrom(r.from);setTo(r.to);setPage(1)}
 const max=Math.max(1,...(data?.daily||[]).map(x=>x.commission));
 const csv=()=>{if(!data)return;const lines=[["Data","Pedidos","Comissão estimada (R$)","Itens vendidos","Valor dos pedidos (R$)"],...data.daily.slice().reverse().map(x=>[x.date,x.orders,x.commission,x.units,x.gmv])];const content=lines.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(";")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+content],{type:"text/csv"}));a.download=`shopee-analytics-${from}-${to}.csv`;a.click();URL.revokeObjectURL(a.href)};
 return <AppShell title="Shopee Analytics" subtitle="Acompanhe suas vendas, pedidos e comissões em um só lugar." action={<button onClick={()=>void load(true)} disabled={syncing} className="inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-black px-4 text-sm font-medium text-white disabled:opacity-50"><RefreshCw size={16} className={syncing?"animate-spin":""}/>{syncing?"Atualizando...":"Atualizar"}</button>}>
  <div className="space-y-6">
   <section className="rounded-xl border border-[#DCE7F7] bg-white p-4"><div className="flex flex-wrap items-end gap-3"><div className="flex flex-wrap gap-2">{[["yesterday","Ontem"],["7","7 dias"],["month","Este mês"]].map(([k,l])=>{const selected=from===presetRange(k).from&&to===presetRange(k).to;return <button key={k} onClick={()=>quick(k)} className={`h-10 rounded-lg border px-3 text-sm transition ${selected?"border-[#BFDBFE] bg-[#EFF6FF] font-medium text-[#2563EB]":"border-line hover:bg-wash"}`}>{l}</button>})}</div><label className="text-xs text-muted">Data inicial<input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1)}} className="focus-ring mt-1 block h-10 rounded-lg border border-[#DCE7F7] px-3 text-sm text-ink"/></label><label className="text-xs text-muted">Data final<input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1)}} className="focus-ring mt-1 block h-10 rounded-lg border border-[#DCE7F7] px-3 text-sm text-ink"/></label>{data?.sync?.last_success_at?<span className="pb-2 text-xs text-muted">Atualizado em {new Date(data.sync.last_success_at).toLocaleString("pt-BR")}</span>:null}</div></section>
   {error?<ErrorState message={error}/>:loading&&!data?<LoadingState/>:data&&!data.connected?<section className="rounded-xl border border-line bg-white p-12 text-center"><ShoppingBag className="mx-auto text-muted" size={36}/><h2 className="mt-4 text-lg font-semibold">Conecte sua conta Shopee</h2><p className="mx-auto mt-2 max-w-lg text-sm text-muted">Conecte sua conta Shopee ao Disparei para acompanhar suas vendas, pedidos e comissões em um só lugar.</p><Link href="/integracoes" className="mt-5 inline-flex h-10 items-center rounded-lg bg-black px-4 text-sm font-medium text-white">Conectar Shopee</Link></section>:data?<>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><HighlightKpi value={money.format(data.summary.estimated)} confirmed={money.format(data.summary.confirmed)} pending={money.format(data.summary.pending)}/><Kpi title="VENDAS GERADAS" value={money.format(data.summary.gmv)} hint="GMV total — pode incluir pedidos ainda pendentes." icon={<TrendingUp size={18}/>} iconBg="bg-emerald-50" iconColor="text-emerald-600"/><Kpi title="PEDIDOS" value={String(data.summary.orders)} hint={`${data.summary.pendingOrders} pedidos pendentes`} icon={<Package size={18}/>} iconBg="bg-amber-50" iconColor="text-amber-600"/><Kpi title="ITENS VENDIDOS" value={String(data.summary.units)} hint="Quantidade total de unidades vendidas." icon={<Boxes size={18}/>} iconBg="bg-[#EFF6FF]" iconColor="text-[#2563EB]"/></div>
    <div className="flex items-start gap-3 rounded-lg border border-[#DCE7F7] bg-[#EFF6FF] px-4 py-3 text-sm text-slate-600"><Info size={16} className="mt-0.5 shrink-0 text-[#2563EB]"/><p>Vendas Geradas e Pedidos podem incluir vendas ainda pendentes. A Comissão Confirmada considera conversões marcadas como concluídas pela Shopee.</p></div>
    <div className="grid gap-6 xl:grid-cols-2"><Ranking title="Top 5 Produtos" icon={<Package size={16}/>} rows={data.topProducts.map(x=>({name:x.name,label:`${x.units} itens`,value:money.format(x.commission)}))}/><Ranking title="Top 5 Lojas" icon={<ShoppingBag size={16}/>} rows={data.topShops.map(x=>({name:x.name,label:`${x.orders} pedidos`,value:money.format(x.commission)}))}/></div>
    <section className="rounded-xl border border-[#DCE7F7] bg-white p-5"><h2 className="font-semibold">Comissão por dia</h2>{data.daily.length?<div className="mt-6 flex h-52 items-end gap-2 overflow-x-auto border-b border-line px-2">{data.daily.map(x=><div key={x.date} title={`${new Date(x.date+"T12:00:00").toLocaleDateString("pt-BR")} — ${money.format(x.commission)}`} className="flex h-full min-w-12 flex-1 flex-col justify-end"><div className="mx-auto w-full max-w-16 rounded-t bg-emerald-500" style={{height:`${Math.max(3,(x.commission/max)*85)}%`}}/><span className="py-2 text-center text-[10px] text-muted">{x.date.slice(8,10)}/{x.date.slice(5,7)}</span></div>)}</div>:<Empty/>}</section>
    <section className="overflow-hidden rounded-xl border border-[#DCE7F7] bg-white"><div className="flex items-center justify-between border-b border-line p-5"><h2 className="font-semibold">Performance Diária</h2><button onClick={csv} className="inline-flex h-9 items-center gap-2 rounded-lg border border-[#DCE7F7] px-3 text-sm transition hover:bg-[#EFF6FF]"><Download size={15}/>Exportar</button></div><Table headers={["Data","Pedidos","Comissão est.","Itens vendidos","Valor dos pedidos"]} rows={data.daily.slice().reverse().map(x=>[new Date(x.date+"T12:00:00").toLocaleDateString("pt-BR"),x.orders,money.format(x.commission),x.units,money.format(x.gmv)])}/></section>
    <section className="overflow-hidden rounded-xl border border-[#DCE7F7] bg-white"><div className="border-b border-line p-5"><h2 className="font-semibold">Dados Detalhados</h2><div className="mt-4 flex flex-wrap gap-3"><label className="relative min-w-64 flex-1"><Search className="absolute left-3 top-3 text-muted" size={16}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Buscar produto ou nº pedido" className="focus-ring h-10 w-full rounded-lg border border-line pl-9 pr-3 text-sm"/></label><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className="focus-ring h-10 rounded-lg border border-line px-3 text-sm"><option value="ALL">Todos os status</option>{data.statusOptions.map(x=><option key={x} value={x}>{statusLabels[x]||x}</option>)}</select></div></div><Table headers={["Pedido","Status","Data","Produto","Loja","Valor","Comissão","%"]} columnWidths={["w-[12%]","w-[9%]","w-[12%]","w-[26%]","w-[13%]","w-[10%]","w-[10%]","w-[8%]"]} align={["left","left","left","left","left","right","right","right"]} rows={data.details.rows.map(x=>[x.order_id,<ShopeeStatusBadge key="status" status={x.conversion_status}/>,new Date(x.purchase_time).toLocaleString("pt-BR"),x.item_name,x.shop_name,money.format(x.actual_amount),<span key="commission" className="font-medium text-[#10B981]">{money.format(x.commission)}</span>,`${Number((x.seller_commission_rate||0)+(x.shopee_commission_rate||0)).toLocaleString("pt-BR",{maximumFractionDigits:2})}%`])}/><div className="flex flex-wrap items-center justify-between gap-3 border-t border-line p-4 text-sm text-muted"><span>{data.details.total} registros</span><div className="flex items-center gap-2"><select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}} className="focus-ring h-9 rounded border border-line px-2">{[20,50,100].map(x=><option key={x}>{x}</option>)}</select><button disabled={page===1} onClick={()=>setPage(x=>x-1)} className="h-9 rounded border border-line px-3 transition hover:enabled:bg-[#EFF6FF] disabled:opacity-40">Anterior</button><span>Página {page}</span><button disabled={page*pageSize>=data.details.total} onClick={()=>setPage(x=>x+1)} className="h-9 rounded border border-line px-3 transition hover:enabled:bg-[#EFF6FF] disabled:opacity-40">Próxima</button></div></div></section>
   </>:null}
  </div>
 </AppShell>
}
function Kpi({title,value,hint,icon,iconBg,iconColor}:{title:string;value:string;hint?:string;icon?:React.ReactNode;iconBg?:string;iconColor?:string}){return <div className="rounded-xl border border-[#DCE7F7] bg-white p-5"><div className="flex items-center justify-between gap-3"><div className="text-xs font-semibold text-muted">{title}</div>{icon?<div className={`grid h-8 w-8 shrink-0 place-items-center rounded-lg ${iconBg} ${iconColor}`}>{icon}</div>:null}</div><div className="mt-3 text-2xl font-semibold">{value}</div>{hint?<p className="mt-2 text-xs text-muted">{hint}</p>:null}</div>}
function HighlightKpi({value,confirmed,pending}:{value:string;confirmed:string;pending:string}){return <div className="rounded-xl border border-[#DCE7F7] bg-[#EFF6FF] p-5"><div className="flex items-center justify-between gap-3"><div className="text-xs font-semibold text-muted">COMISSÃO ESTIMADA</div><div className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-white text-[#2563EB]"><Wallet size={18}/></div></div><div className="mt-3 text-2xl font-semibold text-ink">{value}</div><div className="mt-3 flex flex-col gap-1 text-xs"><span className="text-muted">Confirmado <b className="text-[#10B981]">{confirmed}</b></span><span className="text-muted">Pendente <b className="text-[#F59E0B]">{pending}</b></span></div></div>}
function Ranking({title,icon,rows}:{title:string;icon?:React.ReactNode;rows:{name:string;label:string;value:string}[]}){return <section className="rounded-xl border border-[#DCE7F7] bg-white p-5"><h2 className="flex items-center gap-2 font-semibold">{icon?<span className="text-[#2563EB]">{icon}</span>:null}{title}</h2>{rows.length?<div className="mt-4 divide-y divide-[#DCE7F7]">{rows.map((x,i)=><div key={`${x.name}-${i}`} className="grid grid-cols-[28px_minmax(0,1fr)_auto] items-center gap-3 py-3"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#EFF6FF] text-xs font-semibold text-[#2563EB]">{i+1}</span><div className="min-w-0"><div className="truncate text-sm font-medium">{x.name}</div><div className="text-xs text-muted">{x.label}</div></div><b className="text-sm text-[#10B981]">{x.value}</b></div>)}</div>:<Empty/>}</section>}
function Table({headers,rows,columnWidths,align}:{headers:string[];rows:React.ReactNode[][];columnWidths?:string[];align?:("left"|"right")[]}){
 const alignCls=(j:number)=>align?.[j]==="right"?"text-right":"text-left";
 return rows.length?<div className="overflow-x-auto"><table className={`w-full text-sm ${columnWidths?"table-fixed":"min-w-[820px] text-left"}`}><thead className="bg-wash text-xs text-muted"><tr>{headers.map((x,i)=><th key={x} className={`px-3 py-3 font-medium ${columnWidths?.[i]||""} ${columnWidths?alignCls(i):""}`}>{x}</th>)}</tr></thead><tbody className="divide-y divide-line">{rows.map((row,i)=><tr key={i} className="hover:bg-wash/60">{row.map((cell,j)=><td key={j} className={`truncate px-3 py-3 ${columnWidths?`${columnWidths[j]} ${alignCls(j)}`:"max-w-72"}`}>{cell}</td>)}</tr>)}</tbody></table></div>:<div className="p-8"><Empty/></div>}
function ShopeeStatusBadge({status}:{status:string}){
 const cls:Record<string,string>={PENDING:"bg-amber-50 text-amber-700 border-amber-200",COMPLETED:"bg-emerald-50 text-emerald-700 border-emerald-200",CANCELLED:"bg-red-50 text-red-700 border-red-200",UNPAID:"bg-slate-100 text-slate-600 border-slate-200"};
 return <span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-medium ${cls[status]||"bg-slate-100 text-slate-600 border-slate-200"}`}>{statusLabels[status]||status}</span>;
}
function Empty(){return <p className="py-8 text-center text-sm text-muted">Nenhum dado encontrado neste período.</p>}
