"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AppShell, EmptyState, ErrorState, LoadingState } from "@/components/ui";

type Analytics = { totals: { started:number; sent:number; delivered:number; deliveryRate:number|null; read:number; readRate:number|null; uniqueClicks:number; joins:number; failures:number; failureRate:number|null }; flows: Array<{id:string;name:string;started:number;deliveryRate:number|null;readRate:number|null;finalConversion:number|null;joins:number;failureRate:number|null}>; steps: Array<{id:string;flow_id:string;name:string;position:number;reached:number;sent:number;delivered:number;deliveryRate:number|null;read:number;readRate:number|null;failed:number;ctas:Array<{id:string;label:string;uniqueClicks:number;totalClicks:number;ctrRead:number|null;ctrDelivered:number|null}>}> };
const fmt = new Intl.NumberFormat("pt-BR"); const rate=(n:number|null)=>n === null ? "—" : `${n.toLocaleString("pt-BR",{maximumFractionDigits:1})}%`;
function Card({label,value,rateValue,tone}:{label:string;value:number;rateValue?:number|null;tone?:string}) { return <div className={`rounded-xl border p-4 ${tone || "border-line bg-white"}`}><p className="text-sm text-muted">{label}</p><p className="mt-1 text-2xl font-semibold text-ink">{fmt.format(value)}</p>{rateValue !== undefined ? <p className="mt-1 text-sm text-muted">{rate(rateValue)}</p> : null}</div>; }

export default function OperacaoWhatsAppPage() {
  const [period,setPeriod]=useState("30d"), [type,setType]=useState("all"), [flowId,setFlowId]=useState(""), [data,setData]=useState<Analytics|null>(null), [loading,setLoading]=useState(true), [error,setError]=useState("");
  const dates=useMemo(()=>{ const end=new Date(); const start=new Date(end); if(period==="today") start.setHours(0,0,0,0); else if(period==="24h") start.setHours(start.getHours()-24); else if(period==="7d") start.setDate(start.getDate()-7); else if(period==="month") start.setDate(1); else start.setDate(start.getDate()-30); return {start:start.toISOString(),end:end.toISOString()}; },[period]);
  useEffect(()=>{ let active=true; setLoading(true); const p=new URLSearchParams({...dates,type}); if(flowId)p.set("flowId",flowId); fetch(`/api/admin/official/analytics?${p}`,{cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);if(active){setData(j.analytics);setError("");}}).catch(e=>active&&setError(e.message||"Falha ao carregar métricas.")).finally(()=>active&&setLoading(false));return()=>{active=false};},[dates,type,flowId]);
  const selectedSteps=data?.steps.filter(s=>!flowId||s.flow_id===flowId)||[];
  return <AppShell title="WhatsApp Oficial" subtitle="Operação e performance da API Oficial da Meta"><div className="space-y-6">
    <nav className="flex flex-wrap gap-2 border-b border-line pb-4"><span className="rounded-lg bg-black px-3 py-2 text-sm font-medium text-white">Visão Geral</span><Link href="/admin/whatsapp-oficial/fluxos" className="rounded-lg border border-line px-3 py-2 text-sm font-medium text-ink hover:bg-wash">Automações</Link><Link href="/admin/whatsapp-oficial/disparos" className="rounded-lg border border-line px-3 py-2 text-sm font-medium text-ink hover:bg-wash">Disparos 1x1</Link></nav>
    <section className="flex flex-wrap gap-3 rounded-xl border border-line bg-panel p-4"><select value={period} onChange={e=>setPeriod(e.target.value)} className="h-10 rounded-lg border border-line bg-white px-3 text-sm"><option value="today">Hoje</option><option value="24h">Últimas 24 horas</option><option value="7d">Últimos 7 dias</option><option value="30d">Últimos 30 dias</option><option value="month">Este mês</option></select><select value={type} onChange={e=>setType(e.target.value)} className="h-10 rounded-lg border border-line bg-white px-3 text-sm"><option value="all">Todos os tipos</option><option value="automation">Automações</option><option value="broadcast">Disparos 1x1</option></select><select value={flowId} onChange={e=>setFlowId(e.target.value)} className="h-10 min-w-48 rounded-lg border border-line bg-white px-3 text-sm"><option value="">Todos os fluxos</option>{data?.flows.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></section>
    {loading?<LoadingState/>:error?<ErrorState message={error}/>:!data?<EmptyState title="Sem dados" description="Nenhum dado disponível para este período."/>:<>
      <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7"><Card label="Pessoas iniciadas" value={data.totals.started}/><Card label="Mensagens enviadas" value={data.totals.sent}/><Card label="Entregues" value={data.totals.delivered} rateValue={data.totals.deliveryRate}/><Card label="Lidas" value={data.totals.read} rateValue={data.totals.readRate}/><Card label="Cliques únicos" value={data.totals.uniqueClicks}/><Card label="Entradas no grupo" value={data.totals.joins}/><Card label="Falhas" value={data.totals.failures} rateValue={data.totals.failureRate} tone="border-red-200 bg-red-50"/></section>
      {!flowId?<section><h2 className="mb-3 text-lg font-semibold text-ink">Performance por fluxo</h2>{data.flows.length?<div className="overflow-x-auto rounded-xl border border-line bg-white"><table className="w-full text-left text-sm"><thead className="bg-wash text-muted"><tr><th className="p-3">Fluxo</th><th>Iniciaram</th><th>Entrega</th><th>Leitura</th><th>Conversão final</th><th>Entraram</th><th>Falhas</th></tr></thead><tbody>{data.flows.map(f=><tr key={f.id} className="border-t border-line"><td className="p-3"><button className="font-medium text-ink hover:underline" onClick={()=>setFlowId(f.id)}>{f.name}</button></td><td>{fmt.format(f.started)}</td><td>{rate(f.deliveryRate)}</td><td>{rate(f.readRate)}</td><td>{rate(f.finalConversion)}</td><td>{fmt.format(f.joins)}</td><td className={f.failureRate&&f.failureRate>3?"text-red-700":""}>{rate(f.failureRate)}</td></tr>)}</tbody></table></div>:<EmptyState title="Nenhum fluxo neste período" description="Os dados começarão a aparecer quando houver mensagens atribuídas."/>}</section>:<section><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-semibold text-ink">Detalhe por etapas</h2><button className="text-sm text-muted hover:text-ink" onClick={()=>setFlowId("")}>Ver todos os fluxos</button></div>{selectedSteps.length?<div className="space-y-3">{selectedSteps.map((s,i)=><div key={s.id} className="rounded-xl border border-line bg-white p-5"><div className="flex items-baseline justify-between"><h3 className="font-semibold text-ink">Etapa {s.position} — {s.name}</h3><span className="text-sm text-muted">{fmt.format(s.reached)} chegaram</span></div><div className="mt-4 grid gap-3 sm:grid-cols-4"><Card label="Enviadas" value={s.sent}/><Card label="Entregues" value={s.delivered} rateValue={s.deliveryRate}/><Card label="Lidas" value={s.read} rateValue={s.readRate}/><Card label="Falhas" value={s.failed}/></div>{s.ctas.map(c=><div key={c.id} className="mt-4 rounded-lg bg-wash p-3 text-sm"><span className="font-medium text-ink">CTA: {c.label}</span><span className="ml-3 text-muted">{fmt.format(c.uniqueClicks)} pessoas clicaram · {fmt.format(c.totalClicks)} cliques totais · CTR lidos {rate(c.ctrRead)} · CTR entregues {rate(c.ctrDelivered)}</span></div>)}{i<selectedSteps.length-1?<p className="mt-3 text-sm text-muted">↓ Próxima etapa: a conversão é calculada pela chegada à etapa seguinte.</p>:null}</div>)}</div>:<EmptyState title="Sem etapas com dados" description="Esse fluxo pode ser legado ou ainda não teve mensagens neste período."/>}</section>}</>}
  </div></AppShell>;
}
