"use client";

import { AppShell, ErrorState, LoadingState } from "@/components/ui";
import { Box, Link2, Pencil, Settings2, ShoppingBag, Unplug } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

type Integration = { app_id?: string | null; status?: string | null; affiliate_tag?: string | null; external_account_label?: string | null; last_error?: string | null } | null;
type Data = { shopee: Integration; mercado_livre: Integration; amazon: Integration };

function statusMeta(status?: string | null) {
  if (status === "connected") return { label: "Conectado", cls: "border-emerald-200 bg-emerald-50 text-emerald-800", dot: "bg-emerald-500" };
  if (status === "connecting" || status === "pending") return { label: "Configuração pendente", cls: "border-amber-200 bg-amber-50 text-amber-800", dot: "bg-amber-500" };
  if (status === "error" || status === "expired") return { label: "Erro na conexão", cls: "border-red-200 bg-red-50 text-red-800", dot: "bg-red-500" };
  return { label: "Não configurado", cls: "border-zinc-200 bg-zinc-50 text-zinc-700", dot: "bg-zinc-400" };
}

export default function IntegracoesPage() {
  const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [appId, setAppId] = useState(""); const [secret, setSecret] = useState(""); const [savingShopee, setSavingShopee] = useState(false); const [connectingMl, setConnectingMl] = useState(false);
  const load = useCallback(async () => { try { const response = await fetch("/api/integracoes", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body); setAppId(body.shopee?.app_id || ""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível carregar as integrações."); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function connectShopee() { setSavingShopee(true); setError(""); try { const response = await fetch("/api/integracoes/shopee", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ app_id: appId, app_secret: secret }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setSecret(""); setNotice("Shopee conectada com sucesso."); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível conectar a Shopee."); } finally { setSavingShopee(false); } }
  async function connectMercadoLivre() { setConnectingMl(true); setError(""); try { const response = await fetch("/api/integracoes/mercado-livre", { method: "POST" }); const body = await response.json(); if (!response.ok) throw new Error(body.error); const result = await new Promise<{ ok: boolean; error?: string }>((resolve, reject) => { const listener = (event: MessageEvent) => { if (event.origin !== window.location.origin || event.data?.type !== "DISPAREI_ML_CONNECTION_RESULT") return; window.clearTimeout(timeout); window.removeEventListener("message", listener); resolve(event.data); }; const timeout = window.setTimeout(() => { window.removeEventListener("message", listener); reject(new Error("A extensão Disparei — Mercado Livre não respondeu.")); }, 15_000); window.addEventListener("message", listener); window.postMessage({ type: "DISPAREI_ML_CONNECT", nonce: body.nonce, backendOrigin: window.location.origin }, window.location.origin); }); if (!result.ok) throw new Error(result.error || "A extensão não conseguiu validar o Mercado Livre."); setNotice("Extensão vinculada. Estamos verificando a geração de link."); window.setTimeout(() => void load(), 4_000); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível conectar ao Mercado Livre."); } finally { setConnectingMl(false); } }
  async function disconnect(provider: "shopee" | "mercado-livre") { if (!window.confirm("Desconectar esta integração?")) return; setError(""); try { const response = await fetch(`/api/integracoes/${provider}`, { method: "DELETE" }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setNotice("Integração desconectada."); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível desconectar."); } }
  return <AppShell title="Integrações" subtitle="Conecte seus marketplaces uma vez e use suas contas em todos os recursos da Disparei.">
    {error ? <div className="mb-4"><ErrorState message={error}/></div> : null}{notice ? <div className="mb-4 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{notice}</div> : null}
    {!data ? <LoadingState/> : <div className="grid max-w-5xl gap-5 lg:grid-cols-3">
      <IntegrationCard name="Shopee" description="Use sua conta de afiliado no Piloto Automático e no Catálogo." icon={<ShoppingBag size={24}/>} color="bg-[#fff0eb] text-[#ee4d2d]" integration={data.shopee} onDisconnect={() => void disconnect("shopee")}>
        <div className="grid gap-3"><label className="text-sm font-medium">App ID<input value={appId} onChange={event => setAppId(event.target.value)} autoComplete="off" className="focus-ring mt-1.5 h-10 w-full rounded-lg border border-line px-3 text-sm"/></label><label className="text-sm font-medium">App Secret<input type="password" value={secret} onChange={event => setSecret(event.target.value)} autoComplete="new-password" placeholder={data.shopee ? "Informe para substituir" : "App Secret"} className="focus-ring mt-1.5 h-10 w-full rounded-lg border border-line px-3 text-sm"/></label></div><button onClick={() => void connectShopee()} disabled={savingShopee || !appId || !secret} className="mt-4 inline-flex h-10 items-center gap-2 rounded-lg bg-black px-4 text-sm font-medium text-white disabled:opacity-40">{data.shopee?.status === "connected" ? <Pencil size={15}/> : <Settings2 size={15}/>}{savingShopee ? "Testando..." : data.shopee?.status === "connected" ? "Editar" : "Configurar"}</button>
      </IntegrationCard>
      <IntegrationCard name="Mercado Livre" description="Conexão individual necessária para gerar seus links de afiliado." icon={<span className="text-lg font-black">ML</span>} color="bg-[#fff8b8] text-zinc-900" integration={data.mercado_livre} onDisconnect={() => void disconnect("mercado-livre")}>
        <button onClick={() => void connectMercadoLivre()} disabled={connectingMl} className="inline-flex h-10 items-center gap-2 rounded-lg bg-black px-4 text-sm font-medium text-white disabled:opacity-40">{data.mercado_livre?.status === "connected" ? <Pencil size={15}/> : <Link2 size={15}/>}{connectingMl ? "Conectando..." : data.mercado_livre?.status === "connected" ? "Verificar conexão" : "Configurar integração"}</button><p className="mt-3 text-xs text-muted">A API administrativa do Catálogo permanece separada e não aparece aqui.</p>
      </IntegrationCard>
      <IntegrationCard name="Amazon" description="Estrutura pronta para conectar sua conta quando o suporte estiver disponível." icon={<Box size={25}/>} color="bg-orange-50 text-orange-700" integration={data.amazon}>
        <button disabled className="inline-flex h-10 items-center gap-2 rounded-lg border border-line bg-white px-4 text-sm font-medium text-muted"><Settings2 size={15}/>Configurar em breve</button>
      </IntegrationCard>
    </div>}
  </AppShell>;
}

function IntegrationCard({ name, description, icon, color, integration, onDisconnect, children }: { name: string; description: string; icon: React.ReactNode; color: string; integration: Integration; onDisconnect?: () => void; children: React.ReactNode }) { const state = statusMeta(integration?.status); const connected = integration?.status === "connected"; const identity = integration?.external_account_label || integration?.affiliate_tag || (integration?.app_id ? `App ID: ${integration.app_id.slice(0, 4)}••••` : null); return <section className="flex min-h-[390px] flex-col rounded-xl border border-line bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div className={`grid h-11 w-11 place-items-center rounded-xl ${color}`}>{icon}</div><span className={`inline-flex items-center gap-2 rounded-full border px-2.5 py-1 text-xs font-medium ${state.cls}`}><span className={`h-1.5 w-1.5 rounded-full ${state.dot}`}/>{state.label}</span></div><h2 className="mt-5 text-lg font-semibold text-ink">{name}</h2><p className="mt-1 min-h-10 text-sm text-muted">{description}</p>{identity ? <div className="mt-4 rounded-lg bg-wash px-3 py-2 text-sm text-ink">{identity}</div> : null}{integration?.last_error && !connected ? <div className="mt-3 text-xs text-red-700">{integration.last_error}</div> : null}<div className="mt-auto pt-5">{children}</div>{connected && onDisconnect ? <button onClick={onDisconnect} className="mt-3 inline-flex h-9 items-center gap-2 text-sm text-red-700"><Unplug size={15}/>Desconectar</button> : null}</section>; }
