begin;

-- Existing cache cannot be attributed reliably to either Shopee account.
-- Keep it for audit under a sentinel that the application never reads.
alter table public.shopee_affiliate_orders
  add column credential_fingerprint text not null default 'legacy';
alter table public.shopee_affiliate_order_items
  add column credential_fingerprint text not null default 'legacy';
alter table public.shopee_affiliate_sync_state
  add column credential_fingerprint text not null default 'legacy';

alter table public.shopee_affiliate_orders
  alter column credential_fingerprint drop default;
alter table public.shopee_affiliate_order_items
  alter column credential_fingerprint drop default;
alter table public.shopee_affiliate_sync_state
  alter column credential_fingerprint drop default;

alter table public.shopee_affiliate_orders
  drop constraint shopee_affiliate_orders_account_id_integration_id_order_id_key;
alter table public.shopee_affiliate_orders
  add constraint shopee_orders_credential_order_key
  unique (account_id, integration_id, credential_fingerprint, order_id);

-- PostgreSQL truncates autogenerated constraint names to 63 bytes.
do $$
declare old_constraint text;
begin
  select c.conname into old_constraint
  from pg_constraint c
  where c.conrelid = 'public.shopee_affiliate_order_items'::regclass
    and c.contype = 'u'
    and pg_get_constraintdef(c.oid) = 'UNIQUE (account_id, integration_id, order_id, item_key)';
  if old_constraint is null then
    raise exception 'Shopee item uniqueness constraint not found';
  end if;
  execute format('alter table public.shopee_affiliate_order_items drop constraint %I', old_constraint);
end $$;
alter table public.shopee_affiliate_order_items
  add constraint shopee_items_credential_order_item_key
  unique (account_id, integration_id, credential_fingerprint, order_id, item_key);

alter table public.shopee_affiliate_sync_state
  drop constraint shopee_affiliate_sync_state_pkey;
alter table public.shopee_affiliate_sync_state
  add constraint shopee_affiliate_sync_state_pkey
  primary key (account_id, integration_id, credential_fingerprint);

create index shopee_orders_credential_period_idx
  on public.shopee_affiliate_orders (account_id, integration_id, credential_fingerprint, purchase_time desc);

commit;
